# Generated by Django 3.2.21 on 2023-11-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='embedding_content',
        ),
    ]
