# Generated by Django 4.2.4 on 2023-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
